spring:
  application:
    name: hsbc-wpb-transaction-management-test
  devtools:
    restart:
      enabled: false
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=5m,expireAfterAccess=2m
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        trace: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  port: 8081
  servlet:
    context-path: /api-test
  tomcat:
    max-threads: 20
    min-spare-threads: 2
    max-connections: 100
    accept-count: 20
    connection-timeout: 2000

# 测试环境特定配置
app:
  test:
    enabled: true
    show-errors: true
    # 测试环境安全配置
    security:
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        max-age: 3600
    # 测试环境性能配置
    performance:
      cache:
        enabled: false
      rate-limit:
        enabled: false
    # 测试环境监控配置
    monitoring:
      enabled: true
      metrics:
        enabled: true
        export:
          prometheus:
            enabled: false
      health:
        enabled: true
        show-details: always

# 测试环境日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    com.hsbc.wpb: DEBUG
    org.springframework.test: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cache: DEBUG
  file:
    name: ./logs/application-test.log
    max-size: 10MB
    max-history: 7
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 测试环境Swagger配置
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  packages-to-scan: com.hsbc.wpb.controller
  paths-to-match: /api/**

# 测试环境事务配置
app:
  transaction:
    max-amount: 1000000
    min-amount: 1
    supported-currencies: USD,EUR,GBP,JPY,CNY
    timeout: 5
    retry:
      max-attempts: 1
      initial-interval: 100
      multiplier: 1.0
      max-interval: 1000
    rate-limit:
      enabled: false
      requests-per-second: 1000

# 测试数据配置
test:
  data:
    enabled: true
    location: classpath:test-data/
    cleanup:
      after-test: true
    mock:
      enabled: true
      timeout: 1000

# 测试环境缓存配置
cache:
  caffeine:
    spec: maximumSize=1000,expireAfterWrite=5m,expireAfterAccess=2m
    transaction:
      spec: maximumSize=500,expireAfterWrite=2m
    account:
      spec: maximumSize=200,expireAfterWrite=5m
    statistics:
      spec: maximumSize=100,expireAfterWrite=1m 